name: Create release

on:
    push:
        branches: [main]

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Check Nixpkgs inputs
              uses: DeterminateSystems/flake-checker-action@main
              with:
                  fail-mode: true

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - uses: DeterminateSystems/magic-nix-cache-action@main


            - name: Build dist
              run: |
                  nix develop --command \
                    just all

            - uses: CupOfTea696/gh-action-auto-release@v1.0.0
              with:
                  title: "Release: $version"
                  tag: "v$semver"
                  draft: false
                  regex: "/^Release: #{semver}$/i"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ./_build/exports/*.*
